### ISSUE TITLE
Add github workflows

### ISSUE THREAD

**Issue by leojonathanoh** [theohbrothers/PSModulePublisher#2]
Don't know whether github workflows will be triggered for a parent project  when a git submodule containing the github workflow `.yml` files is added at `./.github/workflows` in the parent project.

My guess is that it doesn't trigger, unlike azure-pipelines where the workflows `.yml` may be imported at ci job runtime.

**Comment by leojonathanoh** [comment]
I tested and the git submodule method does not work as guessed. No workflow is triggered in https://github.com/leojonathanoh/test-github-actions-parent

This means github workflows may not be able used in a project as a git submodule.

**Comment by leojonathanoh** [comment]
It actually makes sense that a workflows should not be triggered by a file in a remote repository, for security reasons. Hence, every repository should have their own copy of workflows in `.github/workflows/*.yml`. What we can do is use github actions in that workflow, the [action can be dockerized](https://help.github.com/en/actions/configuring-and-managing-workflows/configuring-a-workflow#choosing-the-type-of-actions-for-your-workflow). See https://github.com/actions/hello-world-docker-action as an example.

The idea is to make each `azure-pipelines` [`step`](https://github.com/theohbrothers/PSModulePublisher/tree/v0.3.2/templates/azure-pipelines/steps) call a standalone powershell script, so that that same script can be reused by a github action by adding `Dockerfile` and `action.yml` alongside it. Then, in the parent github workflows `.github/workflows/build.yml`, we simply use `uses: ./build/PSModulePublisher/templates/github-actions/display-systeminfo` to run an action.

**Comment by leojonathanoh** [comment]
> se that a workflows should not be trigger

I realize that we cannot use dockerized `github-actions`  because we are indeed testing powershell on multiple vm platforms (`vmImage`), and all the `Invoke-*` commands should be run on the ci platform itself. 

The only way to make `github-actions` resuable is to create individual javascript github-actions repositories for each `azure-pipelines` [`step`](https://github.com/theohbrothers/PSModulePublisher/tree/v0.3.2/templates/azure-pipelines/steps) we have.

**Comment by leojonathanoh** [comment]
`azure-pipelines` images are converging with `github-actions` images

https://docs.microsoft.com/en-us/azure/devops/pipelines/agents/hosted?view=azure-devops&tabs=yaml#use-a-microsoft-hosted-agent

https://help.github.com/en/actions/reference/virtual-environments-for-github-hosted-runners#supported-runners-and-hardware-resources

It might be time to move on entirely to use github actions, with this project being a submodule containing all the tools used by each github action.

**Comment by joeltimothyoh** [comment]
Unfortunately, GitHub Actions does not yet support splitting of the CI configuration file into composable/reusable CI templates for remote execution like Azure Pipelines and GitLab do. @leojonathanoh

**Comment by leojonathanoh** [comment]
> Unfortunately, GitHub Actions does not yet support splitting of the CI configuration file into composable/reusable CI templates for remote execution like Azure Pipelines and GitLab do. @leojonathanoh

yes. so the project might have to evolve to become a git submodule holding standalone script snippets which are considered tools. Then these snippets are consumed by the ci file by the parent repo, regardless of whether ci templating should be used. @joeltimothyoh

**Comment by joeltimothyoh** [comment]
> yes. so the project might have to evolve to become a git submodule holding standalone script snippets which are considered tools. Then these snippets are consumed by the ci file by the parent repo, regardless of whether ci templating should be used. @joeltimothyoh

The project’s focus is on publishing PowerShell modules. I’m not sure what other scripts and tools are necessary except those that already exist within `/src` and `/tools`. @leojonathanoh

**Comment by joeltimothyoh** [comment]
Until GitHub Actions supports templating of CI files for remote execution, this issue cannot be resolved.

Closing for now.
