### ISSUE TITLE
Use ./src/<MODULE>/modulemanifest.ps1 as module manifest definition

### ISSUE THREAD

**Issue by leojonathanoh** [theohbrothers/PSModulePublisher#8]
## Current

Use `./build/definitions/modulemanifest/definition.ps1` as module manifest definition file.

## Expectation

Use `./src/<MODULE>/modulemanifest.ps1` as module manifest definition file.

## Discussion

As was discussed in https://github.com/theohbrothers/ItemLinkManagement/pull/2#issuecomment-890544601, The best place to place the modulemanifest would be to be right beside the `.psd1` or `.psm1` where most developers would expect. Also, in that location the modulemanifest would see the same folder structure as the `.psm1` and hence be able to populate `Exported*` keys of the module manifest definition dynamically.

**Comment by joeltimothyoh** [comment]
It’ll be a misuse of the definition file just because it’s in `.ps1`.
